server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commushop?serverTimezone=UTC
    username: xxx
    password: xxx  //填写你的用户名和密码
  application:
    name: product-service
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/zzy/mapper/xml/*.xml
