server:
  port: 8083

aliyun:
  accessKey: xxx  
  secret: xxx  //填写你的accessKey和secret
  signature: 阿里云短信测试
  templateCode: SMS_154950909  //填写你的签名和模板码

spring:
  application:
    name: sms-service
  redis:
    database: 0
    host: 192.168.127.136
    port: 6379
    password: Zzy1591
