server:
  port: 8686
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors: #全局跨域配置
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:8383"
              - "http://localhost:8282"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      discovery:
        locator:
          enabled: true